# Generated by Django 5.2 on 2025-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("general_setting", "0002_tradesetting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tradesetting",
            name="account_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
